#!/usr/bin/env bash

gem install bundler
bundle update

mkdir -p test/reports
cd storefront

CI_GEM_PATH="$(bundle show workarea-ci)"
. ${CI_GEM_PATH}/exe/workarea-set-ci-env

bundle exec bin/rails app:workarea:test
mv test/reports/report.xml ../test/reports/storefront.xml
